[package]
name = "keymacros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
evdev = "0.12.1"
input = "0.9.0"
libc = "0.2.153"
once_cell = "1.19.0"
regex = "1.10.3"
